name: Code Checkout

on: push

jobs:
  checkout:
    name: Checkout Code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          token: ${{ secrets.CHECKOUT_SECRET }}