name: Code Checkout

on: push

jobs:
  checkout:
    name: Checkout Code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CHECKOUT_SECRET }}